# .github/workflows/deploy.yml

name: Build and Deploy to Cloud Run

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches: [ "main" ]

# Environment variables available to all jobs
env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: us-west1
  REPO_NAME: computer-vision-artifact-reg-repo # Your Artifact Registry repo name
  API_SERVICE_NAME: access-monitor-api-service   # Your Cloud Run service name
  API_IMAGE_NAME: access-monitor-api           # The name for your Docker image

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GCP_REGION }}-docker.pkg.dev

      - name: Build and Push API Docker image
        run: |-
          docker build -t ${{ env.GCP_REGION }}-docker.pkg.dev/$GCP_PROJECT_ID/$REPO_NAME/$API_IMAGE_NAME:latest -f Dockerfile.api .
          docker push ${{ env.GCP_REGION }}-docker.pkg.dev/$GCP_PROJECT_ID/$REPO_NAME/$API_IMAGE_NAME:latest

      - name: Deploy API to Cloud Run
        run: |-
          gcloud run deploy ${{ env.API_SERVICE_NAME }} \
            --image=${{ env.GCP_REGION }}-docker.pkg.dev/$GCP_PROJECT_ID/$REPO_NAME/$API_IMAGE_NAME:latest \
            --platform=managed \
            --region=$GCP_REGION \
            --allow-unauthenticated